# @see https://zenn.dev/tmknom/books/pragmatic-composite-action/viewer/lint
name: Internal Lint (YAML)
run-name: ${{ github.workflow }}

on:
  pull_request:
    paths: ['**.yml', '**.yaml']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  call:
    uses: gawaooooo-sandbox/learn-github-actions-reusable-workflows/.github/workflows/yaml-lint.yml@v3
    permissions:
      contents: read
