name: Deploy to testing environment
run-name: ${{ github.workflow }}

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'public/**'
      - '.editorconfig'
      - '.gitignore'

jobs:
  lint:
    uses: gawaooooo-sandbox/learn-github-actions-reusable-workflows/.github/workflows/reusable-lint.yml@main
    with:
      install-options: '--ignore-scripts'
      enable-format-check: true
      enable-type-check: true
      typecheck-script: 'npm run type:check'
    permissions:
      contents: read
      packages: read

  test:
    uses: ./.github/workflows/test.yml

  # environment variable を reusable workflow に設定するために OUTPUT を使う
  setup:
    needs: [lint, test]
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    environment: alpha
    outputs:
      BASE_URL: ${{ steps.base-url.outputs.base-url }}
      TEST_HOGE: ${{ steps.test-hoge.outputs.test-hoge }}
    steps:
      - id: base-url
        run: echo "base-url=${{ vars.BASE_URL}}" >> "$GITHUB_OUTPUT"
      - id: test-hoge
        run: echo "test-hoge=${{ vars.TEST_HOGE }}" >> "$GITHUB_OUTPUT"

  merge-branch:
    needs: [setup]
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: write

    steps:
      - name: Merge branch
        uses: everlytic/branch-merge@c4a244dc23143f824ae6c022a10732566cb8e973 # v1.1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # # @see https://docs.github.com/ja/enterprise-cloud@latest/actions/learn-github-actions/contexts#github-context
          # # pull request の マージブランチ(マージ対象のブランチとマージした結果の状態を持つブランチ)をdevelopにマージする
          # source_ref: ${{github.ref}}

          # プルリクエスト元のブランチをdevelopにマージする
          # @see https://docs.github.com/ja/enterprise-cloud@latest/actions/learn-github-actions/contexts#github-context
          source_ref: ${{github.head_ref}}
          target_branch: develop

  deploy:
    needs: [merge-branch, setup]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    uses: gawaooooo-sandbox/learn-github-actions-reusable-workflows/.github/workflows/reusable-deploy.yml@main
    with:
      environment: alpha
      checkout-ref: develop
      build-environments: '["BASE_URL=${{needs.setup.outputs.BASE_URL}}", "TEST_HOGE=${{ needs.setup.outputs.TEST_HOGE }}"]'
      s3-uri: 's3://example-bucket-name'
      use-aws: false
    secrets:
      node-auth-token: ${{ secrets.GITHUB_TOKEN }}
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
    permissions:
      contents: read
      packages: read
      id-token: write
