name: Deploy to Validation Environment

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'public/**'
      - '.editorconfig'
      - '.gitignore'

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  deploy:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      # Add your build and test steps here

      - name: Deploy to testing environment
        run: |
          # Add your deployment commands here
