name: Deploy to Selected Environment
run-name: Deployt to ${{ inputs.environment }} on ${{ github.ref_type }} ${{ github.ref_name }} [${{ github.sha }}]

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (alpha|prod)'
        required: true
        type: environment
        default: 'prod'
      # environment:
      #   description: 'Environment to deploy to'
      #   required: true
      #   type: choice
      #   default: 'prod'
      #   options:
      #     - 'prod'
      #     - 'alpha'

jobs:
  # setup:
  #   runs-on: ubuntu-22.04
  #   outputs:
  #     branch: ${{ steps.checkout.outputs.branch }}
  #   steps:
  #     - name: Checkout branch
  #       id: checkout
  #       # environment == production の場合は main ブランチをチェックアウト
  #       # environment == alpha の場合は develop ブランチをチェックアウト
  #       # それ以外の場合はエラー
  #       run: |
  #         if [[ inputs.environment == 'prod' ]]; then
  #           echo "branch=main" >> $GITHUB_OUTPUT
  #         elif [[ inputs.environment == 'alpha' ]]; then
  #           echo "branch=develop" >> $GITHUB_OUTPUT
  #         else
  #           echo "Invalid environment: ${{ inputs.environment }}"
  #           exit 1
  #         fi

  pre-processing:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: create inputs summary
        uses: gawaooooo-sandbox/learn-github-actions-custom/composite/inputs-summary@main
        with:
          workflow-inputs: ${{ toJSON(inputs) }}

  deploy:
    # needs: setup
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ inputs.environment }}
      cancel-in-progress: true
    environment: ${{ inputs.environment }}

    steps:
      # - name: Set up checkout branch
      #   id: checkout
      #   run: |
      #     if [[ ${{ inputs.environment }} == 'prod' ]]; then
      #       echo "branch=main" >> $GITHUB_OUTPUT
      #     elif [[ ${{ inputs.environment }} == 'alpha' ]]; then
      #       echo "branch=develop" >> $GITHUB_OUTPUT
      #     else
      #       echo "Invalid environment: ${{ inputs.environment }}"
      #       exit 1
      #     fi

      # - run: echo ${{ steps.checkout.outputs.branch }}
      - name: Checkout code
        uses: actions/checkout@v4
        # with:
        #   ref: ${{ steps.checkout.outputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          # CI上では Husky を install しない
          # https://typicode.github.io/husky/how-to.html#ci-server-and-docker
          HUSKY: 0

      - name: Build
        run: npm run generate
        env:
          BASE_URL: ${{vars.BASE_URL}}

      - name: Deploy to testing environment
        run: |
          echo "Deploying to testing environment"
          ls -la dist/
          echo "${{vars.TEST_HOGE}}"
