name: Pre Deploy Check
run-name: ${{ github.workflow }} on ${{ github.ref_type }} ${{ github.ref_name }} [${{ github.sha }}]

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'public/**'
      - '.editorconfig'
      - '.gitignore'
  workflow_dispatch:

jobs:
  lint:
    # uses: ./.github/workflows/lint.yml
    uses: gawaooooo-sandbox/learn-github-actions-reusable-workflows/.github/workflows/reusable-lint.yml@main
    with:
      checkout-ref: ${{ github.ref }}
      enable-format-check: true
      lint-script: 'npm run lint && npm run format:check'

  test:
    uses: ./.github/workflows/test.yml
    with:
      checkout-ref: ${{ github.ref }}
