name: Test

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '*.md'
      - 'public/**'
      - '.editorconfig'
      - '.gitignore'

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          # CI上では Husky を install しない
          # https://typicode.github.io/husky/how-to.html#ci-server-and-docker
          HUSKY: 0

      - name: Run tests
        # run: npm test
        run: |
          echo "No tests"

        # TODO: e2e test がある場合
