name: Test

on:
  workflow_call:
    inputs:
      node-version:
        description: "Optional input to set the version of Node.js used to build the project. The input syntax corresponds to the setup-node's one"
        required: false
        type: string
      node-version-file:
        description: "Optional input to set the file that contains the version of Node.js used to build the project. The input syntax corresponds to the setup-node's one"
        required: false
        type: string
        default: '.nvmrc'
      node-caching:
        description: "Optional input to set up caching for the setup-node action. The input syntax corresponds to the setup-node's one. Set to an empty string if caching isn't needed"
        required: false
        type: string
        default: 'npm'
      checkout-ref:
        description: "Optional input to set the ref to checkout. The input syntax corresponds to the actions/checkout's one"
        required: false
        type: string
        # TODO: github.ref?
        default: ${{ github.head_ref }}
      install-options:
        description: 'Optional input to set the options to pass to the npm install command'
        required: false
        type: string
      test-script:
        description: 'Optional input to set the script to run the tests'
        required: false
        type: string
        default: 'npm test'
  # workflow_dispatch:
  # push:
  #   paths-ignore:
  #     - '*.md'
  #     - 'public/**'
  #     - '.editorconfig'
  #     - '.gitignore'

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
      # - run: cat $GITHUB_EVENT_PATH

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkout-ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          node-version-file: ${{ inputs.node-version-file }}
          cache: ${{ inputs.node-caching }}

      - name: Install dependencies
        run: npm ci ${{ inputs.install-options }}
        env:
          # CI上では Husky を install しない
          # https://typicode.github.io/husky/how-to.html#ci-server-and-docker
          HUSKY: 0

      # TODO: test は composite action のほうがいいかもしれない
      - name: Run tests
        run: ${{ inputs.test-script }}
