name: Test

on:
  workflow_call:
    inputs:
      checkout-ref:
        description: "Optional input to set the ref to checkout. The input syntax corresponds to the actions/checkout's one"
        required: false
        type: string
        # TODO: github.ref?
        default: ${{ github.head_ref }}
      install-options:
        description: 'Optional input to set the options to pass to the npm install command'
        required: false
        type: string
      test-script:
        description: 'Optional input to set the script to run the tests'
        required: false
        type: string
        default: 'npm test'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
      - name: Setup Node.js and Install dependencies
        uses: gawaooooo-sandbox/learn-github-actions-custom/composite/node-setup-and-dependencies@v4
        with:
          checkout-ref: ${{ inputs.checkout-ref }}
          npm-install-options: ${{ inputs.install-options }}

      - name: Run tests
        run: ${{ inputs.test-script }}
